desc add_consumer

CREATE SEQUENCE consumer_seq
START WITH    111111
INCREMENT BY   1
NOCACHE   
NOCYCLE;

drop SEQUENCE consumer_seq
SELECT joindate,to_char(joindate,'hh:mi') FROM ADD_CONSUMER
UPDATE ADD_CONSUMER SET JOINDATE = SYSDATE WHERE CON_ID=111111
UPDATE ADD_CONSUMER SET JOINTIME = SYSTIMESTAMP WHERE CON_ID=111111

select sysdate,to_char(sysdate,'hh24:mi:ss') dat from dual

select add_months(to_date('23-08-21','dd-mm-yy'),5),to_date('01/feb/21','dd-mon/yy') from dual

SELECT * FROM ADD_CONSUMER
select * from meter_reading order by con_id

select con_id,count(*) from meter_reading group by con_id




insert into meter_reading select con_id ,200,sysdate from ADD_CONSUMER where con_id<>'111139'

update meter_reading set current_reading=current_reading*rownum

SELECT * FROM CHARGE_MASTER
TRUNCATE TABLE CHARGE_MASTER
INSERT INTO CHARGE_MASTER (CON_ID,SUPPLY_TYPE)  SELECT CON_ID,SUPPLY_TYPE FROM ADD_CONSUMER
UPDATE CHARGE_MASTER M SET CURRENT_UNIT=
(SELECT CURRENT_READING R FROM METER_READING R WHERE R.CON_ID=M.CON_ID AND 
READING_DATE BETWEEN '1-SEP-21' AND '30-SEP-21')
UPDATE CHARGE_MASTER M SET PRE_UNIT=
(SELECT UNIT_CONSUMED FROM CHARGE_MASTER_TRACK T WHERE T.CON_ID=M.CON_ID AND BILL_DATE='10-AUG-21')
UPDATE CHARGE_MASTER M SET PRE_UNIT=0 where pre_unit is null-- CHANGE
-- ADDITIONAL STEP 
UPDATE CHARGE_MASTER M SET UNIT_CONSUMED=CURRENT_UNIT-PRE_UNIT
-- BALANCE AMOUNT CALCULATION
UPDATE CHARGE_MASTER M SET BALANCE_AMT=
(select charge_amT from CHARGE_MASTER_track T where  T.CON_ID=M.CON_ID AND BILL_DATE='10-AUG-21' and bill_status='UNPAID')

UPDATE CHARGE_MASTER M SET BALANCE_AMT=0 WHERE BALANCE_AMT IS NULL

UPDATE CHARGE_MASTER M SET ENERGY_CHAGE=UNIT_CONSUMED*3.05,FIXED_CHARGE=75 WHERE UNIT_CONSUMED<=100
UPDATE CHARGE_MASTER M SET ENERGY_CHAGE=305+(UNIT_CONSUMED-100)*5,FIXED_CHARGE=115
WHERE UNIT_CONSUMED>100 AND UNIT_CONSUMED<=300 
UPDATE CHARGE_MASTER M SET ENERGY_CHAGE=1305+(UNIT_CONSUMED-300)*6.65,FIXED_CHARGE=115
WHERE UNIT_CONSUMED>300 AND UNIT_CONSUMED<=500
UPDATE CHARGE_MASTER M SET ENERGY_CHAGE=2635+(UNIT_CONSUMED-500)*7.8,FIXED_CHARGE=140
WHERE UNIT_CONSUMED>500
UPDATE CHARGE_MASTER M SET WHEELING_CHARGE=UNIT_CONSUMED*1.46
UPDATE CHARGE_MASTER M SET GOV_CHARGE=ROUND((ENERGY_CHAGE+FIXED_CHARGE+WHEELING_CHARGE)*.16,2)

-- UPDATE GOVT CHARGE
UPDATE CHARGE_MASTER M SET CHARGE_AMT=ENERGY_CHAGE+FIXED_CHARGE+WHEELING_CHARGE+GOV_CHARGE+BALANCE_AMT,
BILL_DATE=SYSDATE

--Insert from charge_master to track
INSERT INTO CHARGE_MASTER_TRACK SELECT A.*,'UNPAID',NULL FROM CHARGE_MASTER A

INSERT INTO CHARGE_MASTER_TRACK(CON_ID,SUPPLY_TYPE,BILL_DATE,PRE_UNIT,CURRENT_UNIT,UNIT_CONSUMED,BALANCE_AMT,CHARGE_AMT,FIXED_CHARGE,ENERGY_CHAGE,WHEELING_CHARGE,GOV_CHARGE,BILL_STATUS) 
SELECT CON_ID,SUPPLY_TYPE,BILL_DATE,PRE_UNIT,CURRENT_UNIT,UNIT_CONSUMED,BALANCE_AMT,CHARGE_AMT,FIXED_CHARGE,ENERGY_CHAGE,WHEELING_CHARGE,GOV_CHARGE,'UNPAID' FROM CHARGE_MASTER


SELECT A.*,'UNPAID',NULL FROM CHARGE_MASTER A
SELECT A.*,'UNPAID',NULL FROM CHARGE_MASTER A

CREATE TABLE CHARGE_MASTER_TRACK AS SELECT * FROM CHARGE_MASTER WHERE ROWNUM<10
UPDATE CHARGE_MASTER_TRACK SET BILL_DATE='10-AUG-21'
ALTER TABLE CHARGE_MASTER_TRACK ADD(PAY_DATE DATE)
SELECT * FROM CHARGE_MASTER
SELECT * FROM CHARGE_MASTER_TRACK

DELETE FROM CHARGE_MASTER_TRACK WHERE TRUNC(BILL_DATE)='12-SEP-21'

SELECT * FROM CHARGE_MASTER_TRACK

ALTER TABLE   CHARGE_MASTER_TRACK ADD(BILL_MONTH VARCHAR2(10))

SELECT TO_DATE('SEP-21','MON-YY'),LAST_DAY(TO_DATE('SEP-21','MON-YY')) FROM DUAL



   
SELECT * FROM ADD_CONSUMER WHERE CON_ID = (SELECT MAX(CON_ID) FROM ADD_CONSUMER)
SELECT JOINDATE,to_char(JOINDATE,'hh:mi') FROM ADD_CONSUMER

SELECT COUNT(*) FROM meter_reading WHERE CON_ID=111115 
and trunc(reading_date) between trunc(sysdate,'mm') and last_day(sysdate)

select sysdate,trunc(sysdate,'mm'),last_day(sysdate) from dual

alter table meter_reading add(insert_on date)

update meter_reading set reading_date='1-sep-21'

select last_day(max(bill_date)) from charge_master_track 

select count(*) from charge_master_track  where last_day(bill_date)>'1-aug-21'

CREATE TABLE BILLTEST AS select * from charge_master_track WHERE CON_ID IN(111134,111119)

INSERT INTO charge_master_track SELECT * FROM BILLTEST

SELECT CON_ID  FROM charge_master_track WHERE BILL_STATUS='UNPAID' AND
BILL_DATE BETWEEN TRUNC(ADD_MONTHS(SYSDATE,-3),'MM') AND SYSDATE
GROUP BY CON_ID HAVING COUNT(*)>=3

SELECT * FROM  ADD_CONSUMER 
WHERE CON_ID IN(
SELECT CON_ID  FROM charge_master_track WHERE BILL_STATUS='UNPAID' AND
BILL_DATE BETWEEN TRUNC(ADD_MONTHS(SYSDATE,-3),'MM') AND SYSDATE
GROUP BY CON_ID HAVING COUNT(*)>=3
)

SELECT * FROM  ADD_CONSUMER C,charge_master_track T
WHERE C.CON_ID=T.CON_ID AND
C.CON_ID IN(
SELECT CON_ID  FROM charge_master_track WHERE BILL_STATUS='UNPAID' AND
BILL_DATE BETWEEN TRUNC(ADD_MONTHS(SYSDATE,-3),'MM') AND SYSDATE
GROUP BY CON_ID HAVING COUNT(*)>=3
)
AND BILL_DATE=(SELECT MAX(BILL_DATE) FROM CHARGE_MASTER_TRACK  )

SELECT * FROM  charge_master_track WHERE CON_ID IN(
SELECT CON_ID  FROM charge_master_track WHERE BILL_STATUS='UNPAID' AND
BILL_DATE BETWEEN TRUNC(ADD_MONTHS(SYSDATE,-3),'MM') AND SYSDATE
GROUP BY CON_ID HAVING COUNT(*)>=3
)

SELECT T1.CON_ID,T1.CON_NAME,T1.PHONE_NO,T2.BALANCE_AMT,to_char(T2.BILL_DATE,'DD-MON-YY'),T2.BILL_STATUS,T2.CHARGE_AMT FROM ADD_CONSUMER T1, CHARGE_MASTER_TRACK T2 
WHERE T1.CON_ID =T2.CON_ID   AND T2.CON_ID = 111115 AND 
BILL_DATE=(SELECT MAX(BILL_DATE) FROM CHARGE_MASTER_TRACK  )

SELECT TRUNC(ADD_MONTHS(SYSDATE,-3),'MM') FROM DUAL

SELECT BILL_STATUS FROM CHARGE_MASTER_TRACK WHERE CON_ID = 111115 AND BILL_DATE =(SELECT MAX(BILL_DATE) FROM CHARGE_MASTER_TRACK)

UPDATE CHARGE_MASTER_TRACK SET BILL_STATUS = 'UNPAID',PAY_DATE = SYSDATE WHERE CON_ID=111119 AND BILL_STATUS = 'PAID'


SELECT CON_ID,

EXEC CHARGE_CALCULATE('SEP-21')

SELECT * FROM CHARGE_MASTER_TRACK WHERE BILL_MONTH='SEP-21'

DELETE FROM CHARGE_MASTER_TRACK WHERE BILL_MONTH='SEP-21'

SELECT * FROM METER_READING WHERE CON_ID='111119'

SELECT * FROM CHARGE_MASTER_TRACK WHERE CON_ID='111119'


UPDATE CHARGE_MASTER M SET CURRENT_UNIT=
(SELECT CURRENT_UNIT+UNIT_CONSUMED FROM CHARGE_MASTER_TRACK T WHERE T.CON_ID=M.CON_ID 
AND BILL_DATE=(SELECT MAX(BILL_DATE) FROM CHARGE_MASTER_TRACK)) WHERE CURRENT_UNIT IS NULL;

UPDATE CHARGE_MASTER M SET CURRENT_UNIT=0 WHERE CURRENT_UNIT IS NULL;

SELECT * FROM CHARGE_MASTER



