CREATE OR REPLACE PROCEDURE CHARGE_CALCULATE (CHARGE_MONTH VARCHAR2) AS
START_DATE DATE;
END_DATE DATE;
BEGIN
SELECT TO_DATE(CHARGE_MONTH,'MON-YY') INTO START_DATE FROM DUAL ;
SELECT LAST_DAY(TO_DATE(CHARGE_MONTH,'MON-YY')) INTO END_DATE FROM DUAL ;
EXECUTE IMMEDIATE 'TRUNCATE TABLE CHARGE_MASTER';
INSERT INTO CHARGE_MASTER (CON_ID,SUPPLY_TYPE)  SELECT CON_ID,SUPPLY_TYPE FROM ADD_CONSUMER;

UPDATE CHARGE_MASTER M SET CURRENT_UNIT=
(SELECT CURRENT_READING R FROM METER_READING R WHERE R.CON_ID=M.CON_ID AND 
READING_DATE BETWEEN START_DATE AND END_DATE);

UPDATE CHARGE_MASTER M SET PRE_UNIT=
(SELECT CURRENT_UNIT FROM CHARGE_MASTER_TRACK T WHERE T.CON_ID=M.CON_ID 
AND BILL_DATE=(SELECT MAX(BILL_DATE) FROM CHARGE_MASTER_TRACK));

UPDATE CHARGE_MASTER M SET PRE_UNIT=0 where pre_unit is null;-- CHANGE

UPDATE CHARGE_MASTER M SET CURRENT_UNIT=
(SELECT CURRENT_UNIT+UNIT_CONSUMED FROM CHARGE_MASTER_TRACK T WHERE T.CON_ID=M.CON_ID 
AND BILL_DATE=(SELECT MAX(BILL_DATE) FROM CHARGE_MASTER_TRACK)) WHERE CURRENT_UNIT IS NULL;

UPDATE CHARGE_MASTER M SET CURRENT_UNIT=0 WHERE CURRENT_UNIT IS NULL;

-- ADDITIONAL STEP 
UPDATE CHARGE_MASTER M SET UNIT_CONSUMED=CURRENT_UNIT-PRE_UNIT;
-- BALANCE AMOUNT CALCULATION
UPDATE CHARGE_MASTER M SET BALANCE_AMT=
(select charge_amT from CHARGE_MASTER_track T where  T.CON_ID=M.CON_ID 
AND BILL_DATE=(SELECT MAX(BILL_DATE) FROM CHARGE_MASTER_TRACK) and bill_status='UNPAID');

UPDATE CHARGE_MASTER M SET BALANCE_AMT=0 WHERE BALANCE_AMT IS NULL;

UPDATE CHARGE_MASTER M SET ENERGY_CHAGE=UNIT_CONSUMED*3.05,FIXED_CHARGE=75 WHERE UNIT_CONSUMED<=100;
UPDATE CHARGE_MASTER M SET ENERGY_CHAGE=305+(UNIT_CONSUMED-100)*5,FIXED_CHARGE=115
WHERE UNIT_CONSUMED>100 AND UNIT_CONSUMED<=300 ;
UPDATE CHARGE_MASTER M SET ENERGY_CHAGE=1305+(UNIT_CONSUMED-300)*6.65,FIXED_CHARGE=115
WHERE UNIT_CONSUMED>300 AND UNIT_CONSUMED<=500;
UPDATE CHARGE_MASTER M SET ENERGY_CHAGE=2635+(UNIT_CONSUMED-500)*7.8,FIXED_CHARGE=140
WHERE UNIT_CONSUMED>500;
UPDATE CHARGE_MASTER M SET WHEELING_CHARGE=UNIT_CONSUMED*1.46;
UPDATE CHARGE_MASTER M SET GOV_CHARGE=ROUND((ENERGY_CHAGE+FIXED_CHARGE+WHEELING_CHARGE)*.16,2);

-- UPDATE GOVT CHARGE
UPDATE CHARGE_MASTER M SET CHARGE_AMT=ENERGY_CHAGE+FIXED_CHARGE+WHEELING_CHARGE+GOV_CHARGE+BALANCE_AMT,
BILL_DATE=SYSDATE;

--Insert from charge_master to track
INSERT INTO CHARGE_MASTER_TRACK(CON_ID,SUPPLY_TYPE,BILL_DATE,PRE_UNIT,CURRENT_UNIT,UNIT_CONSUMED,BALANCE_AMT,CHARGE_AMT,FIXED_CHARGE,ENERGY_CHAGE,WHEELING_CHARGE,GOV_CHARGE,BILL_STATUS,BILL_MONTH,BILL_NO) 
SELECT CON_ID,SUPPLY_TYPE,BILL_DATE,PRE_UNIT,CURRENT_UNIT,UNIT_CONSUMED,BALANCE_AMT,CHARGE_AMT,FIXED_CHARGE,ENERGY_CHAGE,WHEELING_CHARGE,GOV_CHARGE,'UNPAID',CHARGE_MONTH,BILLNO_SEQ.NEXTVAL FROM CHARGE_MASTER;

UPDATE CHARGE_MASTER_TRACK SET BILL_NO='3'||LPAD(ROWNUM,5,'0') WHERE BILL_NO IS NULL;
END;



